// templates/apps/tauri-react/app/src/components/notes-list.tsx
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import type { NotesState } from "@/hooks/use-notes";

interface Props {
  state: NotesState;
  onRetry: () => void;
}

export function NotesList({ state, onRetry }: Props) {
  if (state.status === "loading") {
    return (
      <div className="flex flex-col gap-3" role="status" aria-label="Loading notes">
        <Skeleton className="h-20 w-full" />
        <Skeleton className="h-20 w-full" />
      </div>
    );
  }

  if (state.status === "error") {
    return (
      <Alert variant="destructive" role="alert">
        <AlertTitle>Could not load notes</AlertTitle>
        <AlertDescription>
          <p>{state.message}</p>
          <Button variant="outline" onClick={onRetry} className="mt-2 h-11">
            Try again
          </Button>
        </AlertDescription>
      </Alert>
    );
  }

  if (state.notes.length === 0) {
    return (
      <p className="text-muted-foreground rounded-lg border border-dashed p-8 text-center text-sm">
        No notes yet. Add your first note above.
      </p>
    );
  }

  return (
    <ul className="flex flex-col gap-3">
      {state.notes.map((note) => (
        <li key={note.id}>
          <Card>
            <CardHeader>
              <CardTitle>{note.title}</CardTitle>
              <CardDescription>
                <time dateTime={note.createdAt}>{new Date(note.createdAt).toLocaleString()}</time>
              </CardDescription>
            </CardHeader>
            {note.body && <CardContent className="text-sm whitespace-pre-wrap">{note.body}</CardContent>}
          </Card>
        </li>
      ))}
    </ul>
  );
}

// templates/apps/tauri-vue/app/src/components/NotesList.vue
<script setup lang="ts">
import UAlert from '@nuxt/ui/components/Alert.vue'
import UCard from '@nuxt/ui/components/Card.vue'
import USkeleton from '@nuxt/ui/components/Skeleton.vue'
import type { Note } from '@/lib/tauri'

defineProps<{
  status: 'loading' | 'ready' | 'error'
  notes: Note[]
  error: string | null
}>()

defineEmits<{ retry: [] }>()
</script>

<template>
  <div
    v-if="status === 'loading'"
    class="flex flex-col gap-3"
    role="status"
    aria-label="Loading notes"
  >
    <USkeleton class="h-20 w-full" />
    <USkeleton class="h-20 w-full" />
  </div>

  <UAlert
    v-else-if="status === 'error'"
    color="error"
    variant="subtle"
    title="Could not load notes"
    :description="error ?? undefined"
    :actions="[{ label: 'Try again', color: 'neutral', variant: 'outline', size: 'xl', onClick: () => $emit('retry') }]"
    role="alert"
  />

  <p
    v-else-if="notes.length === 0"
    class="rounded-lg border border-dashed border-default p-8 text-center text-sm text-muted"
  >
    No notes yet. Add your first note above.
  </p>

  <ul
    v-else
    class="flex flex-col gap-3"
  >
    <li
      v-for="note in notes"
      :key="note.id"
    >
      <UCard>
        <h3 class="font-medium">
          {{ note.title }}
        </h3>
        <time
          :datetime="note.createdAt"
          class="text-xs text-muted"
        >{{ new Date(note.createdAt).toLocaleString() }}</time>
        <p
          v-if="note.body"
          class="mt-2 whitespace-pre-wrap text-sm"
        >
          {{ note.body }}
        </p>
      </UCard>
    </li>
  </ul>
</template>
