// templates/apps/edge-web-next/app/components/notes-list.tsx
'use client'

import type { Note } from '@/shared/schemas/note'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'

interface NotesListProps {
  notes: Note[] | undefined
  isLoading: boolean
  error: Error | null
  onRetry: () => void
}

export function NotesList({ notes, isLoading, error, onRetry }: NotesListProps) {
  if (isLoading) {
    return (
      <div className="space-y-3">
        {[0, 1, 2].map(n => (
          <Skeleton key={n} data-testid="note-skeleton" className="h-20 w-full" />
        ))}
      </div>
    )
  }

  if (error) {
    return (
      <Alert variant="destructive">
        <AlertTitle>Could not load notes</AlertTitle>
        <AlertDescription>
          <p>{error.message}</p>
          <Button variant="outline" size="sm" className="mt-2" onClick={onRetry}>Retry</Button>
        </AlertDescription>
      </Alert>
    )
  }

  if (!notes?.length) {
    return (
      <div className="rounded-lg border border-dashed p-8 text-center">
        <p className="font-medium">No notes yet</p>
        <p className="text-sm text-muted-foreground">Create your first note with the form above.</p>
      </div>
    )
  }

  return (
    <ul className="space-y-3">
      {notes.map(note => (
        <li key={note.id} data-testid="note">
          <Card>
            <CardHeader>
              <CardTitle>{note.title}</CardTitle>
            </CardHeader>
            {note.body && (
              <CardContent>
                <p className="whitespace-pre-line text-muted-foreground">{note.body}</p>
              </CardContent>
            )}
            <CardFooter>
              <time dateTime={note.createdAt} className="text-xs text-muted-foreground">
                {new Date(note.createdAt).toLocaleString()}
              </time>
            </CardFooter>
          </Card>
        </li>
      ))}
    </ul>
  )
}

// templates/apps/edge-web-nuxt/app/app/components/NotesList.vue
<script setup lang="ts">
import type { Note } from '#shared/schemas/note'

defineProps<{
  notes: Note[]
  /** Fetch status from useFetch. */
  status: 'idle' | 'pending' | 'success' | 'error'
  error?: string
}>()

defineEmits<{ retry: [] }>()
</script>

<template>
  <div class="space-y-3">
    <template v-if="status === 'pending' && !notes.length">
      <USkeleton v-for="n in 3" :key="n" data-testid="note-skeleton" class="h-20 w-full" />
    </template>

    <UAlert
      v-else-if="status === 'error'"
      color="error"
      variant="subtle"
      icon="i-lucide-circle-alert"
      title="Could not load notes"
      :description="error"
      :actions="[{ label: 'Retry', color: 'error', variant: 'outline', onClick: () => $emit('retry') }]"
    />

    <UEmpty
      v-else-if="!notes.length"
      icon="i-lucide-notebook-pen"
      title="No notes yet"
      description="Create your first note with the form above."
    />

    <UCard v-for="note in notes" v-else :key="note.id" data-testid="note">
      <template #header>
        <h3 class="font-semibold">
          {{ note.title }}
        </h3>
      </template>
      <p v-if="note.body" class="whitespace-pre-line text-muted">
        {{ note.body }}
      </p>
      <template #footer>
        <time :datetime="note.createdAt" class="text-xs text-dimmed">{{ new Date(note.createdAt).toLocaleString() }}</time>
      </template>
    </UCard>
  </div>
</template>
