// templates/apps/spa-web-react/app/src/pages/login.tsx
import { useRouter, useSearch, Link } from "@tanstack/react-router";
import { LoaderCircle } from "lucide-react";
import { useState } from "react";
import { z } from "zod";
import { Field } from "@/components/field";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { fieldProps } from "@/lib/field-props";
import { safeRedirect } from "@/lib/redirect";
import { useTitle } from "@/lib/use-title";
import { useZodForm } from "@/lib/use-zod-form";
import { useProviders, useRequestMagicLink, useSignIn } from "@/queries/auth";

const emailMessage = "Enter a valid email address, like name@example.com";
const passwordSchema = z.object({ email: z.email(emailMessage), password: z.string().min(1, "Enter your password") });
// The API redirects here with ?error=<code> when an OIDC sign-in fails.
function providerErrorText(code: string) {
  return code === "access_denied"
    ? "Access was denied at the provider. Try again, or use another sign-in method."
    : "Something went wrong while signing in with your provider. Try again, or use another sign-in method.";
}

const linkSchema = z.object({ email: z.email(emailMessage) });

function PasswordForm({ redirect }: { redirect: string }) {
  const router = useRouter();
  const signIn = useSignIn();
  const form = useZodForm(passwordSchema, "login");
  const [values, setValues] = useState({ email: "", password: "" });

  function change(next: Partial<typeof values>) {
    const merged = { ...values, ...next };
    setValues(merged);
    form.revalidate(merged);
  }

  function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    const data = form.validate(values);
    if (data) signIn.mutate(data, { onSuccess: () => router.history.push(redirect) });
  }

  return (
    <form onSubmit={onSubmit} className="space-y-4" noValidate>
      <Field id="login-email" label="Email" error={form.errors.email}>
        <Input
          {...fieldProps("login-email", { error: form.errors.email })}
          type="email"
          autoComplete="email"
          value={values.email}
          onChange={(e) => change({ email: e.target.value })}
        />
      </Field>
      <Field id="login-password" label="Password" error={form.errors.password}>
        <Input
          {...fieldProps("login-password", { error: form.errors.password })}
          type="password"
          autoComplete="current-password"
          value={values.password}
          onChange={(e) => change({ password: e.target.value })}
        />
      </Field>
      {signIn.error ? (
        <Alert variant="destructive">
          <AlertTitle>Couldn't sign you in</AlertTitle>
          <AlertDescription>{signIn.error.message}</AlertDescription>
        </Alert>
      ) : null}
      <Button type="submit" className="w-full" disabled={signIn.isPending}>
        {signIn.isPending ? <LoaderCircle className="animate-spin" aria-hidden="true" /> : null}
        Sign in
      </Button>
    </form>
  );
}

function MagicLinkForm() {
  const request = useRequestMagicLink();
  const form = useZodForm(linkSchema, "link");
  const [email, setEmail] = useState("");
  const [sentTo, setSentTo] = useState<string | null>(null);

  if (sentTo) {
    return (
      <Alert data-testid="magic-sent" role="status">
        <AlertTitle>Check your inbox</AlertTitle>
        <AlertDescription>If an account exists for {sentTo}, a sign-in link is on its way. It works once and expires soon.</AlertDescription>
      </Alert>
    );
  }

  function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    const data = form.validate({ email });
    if (data) request.mutate(data.email, { onSuccess: () => setSentTo(data.email) });
  }

  return (
    <form onSubmit={onSubmit} className="space-y-4" noValidate>
      <Field id="link-email" label="Email me a sign-in link" hint="No password needed." error={form.errors.email}>
        <Input
          {...fieldProps("link-email", { hint: "No password needed.", error: form.errors.email })}
          type="email"
          autoComplete="email"
          value={email}
          onChange={(e) => {
            setEmail(e.target.value);
            form.revalidate({ email: e.target.value });
          }}
        />
      </Field>
      {request.error ? (
        <Alert variant="destructive">
          <AlertTitle>Couldn't send the link</AlertTitle>
          <AlertDescription>{request.error.message}</AlertDescription>
        </Alert>
      ) : null}
      <Button type="submit" variant="outline" className="w-full" disabled={request.isPending}>
        {request.isPending ? <LoaderCircle className="animate-spin" aria-hidden="true" /> : null}
        Send sign-in link
      </Button>
    </form>
  );
}

export function LoginPage() {
  useTitle("Sign in");
  const search = useSearch({ strict: false }) as { redirect?: string; error?: string };
  const redirect = safeRedirect(search.redirect);
  const providers = useProviders();

  // Where the OIDC flow lands afterwards; the API validates it is an app-relative path.
  const oidcHref = (id: string) => `/api/v1/auth/oidc/${encodeURIComponent(id)}/start?redirect=${encodeURIComponent(redirect)}`;

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-semibold text-balance">Sign in</h1>

      {search.error ? (
        <Alert variant="destructive" data-testid="provider-error">
          <AlertTitle>Couldn't sign you in</AlertTitle>
          <AlertDescription>{providerErrorText(search.error)}</AlertDescription>
        </Alert>
      ) : null}

      {providers.isPending ? (
        <div data-testid="providers-loading" aria-busy="true" className="space-y-3">
          <Skeleton className="h-9 w-full" />
          <Skeleton className="h-9 w-full" />
          <Skeleton className="h-9 w-full" />
        </div>
      ) : providers.isError ? (
        <Alert variant="destructive" data-testid="providers-error">
          <AlertTitle>Couldn't load the sign-in options</AlertTitle>
          <AlertDescription>The server didn't respond. Check your connection, then try again.</AlertDescription>
          <Button variant="outline" size="sm" className="mt-3" onClick={() => void providers.refetch()}>
            Try again
          </Button>
        </Alert>
      ) : (
        <>
          {providers.data.password ? <PasswordForm redirect={redirect} /> : null}

          {providers.data.password && (providers.data.magicLink || providers.data.oidc.length > 0) ? (
            <p className="text-center text-sm text-muted-foreground">or</p>
          ) : null}

          {providers.data.oidc.length > 0 ? (
            <div className="space-y-3">
              {providers.data.oidc.map((p) => (
                <Button key={p.id} asChild variant="outline" className="w-full" data-testid={`oidc-${p.id}`}>
                  <a href={oidcHref(p.id)}>Continue with {p.name}</a>
                </Button>
              ))}
            </div>
          ) : null}

          {providers.data.magicLink ? <MagicLinkForm /> : null}

          {!providers.data.password && !providers.data.magicLink && providers.data.oidc.length === 0 ? (
            <p data-testid="no-methods" className="text-muted-foreground">
              No sign-in methods are enabled for this app. Ask an administrator to turn one on.
            </p>
          ) : null}

          {providers.data.registration ? (
            <p className="text-sm text-muted-foreground">
              New here?{" "}
              <Link to="/register" search={search.redirect ? { redirect: search.redirect } : {}} className="font-medium text-primary underline-offset-4 hover:underline">
                Create an account
              </Link>
            </p>
          ) : null}
        </>
      )}
    </div>
  );
}

// templates/apps/spa-web-nuxt/app/app/pages/login.vue
<script setup lang="ts">
import { z } from 'zod'
import type { FormErrorEvent, FormSubmitEvent } from '@nuxt/ui'

definePageMeta({ layout: 'auth', public: true, guestOnly: true })
useHead({ title: 'Sign in' })

const route = useRoute()
const redirect = computed(() => safeRedirect(route.query.redirect))
const { signIn, requestMagicLink } = useAuth()
const { providers, status, load } = useAuthProviders()
onMounted(load)

// The API redirects here with ?error=<code> when an OIDC sign-in fails.
const providerError = computed(() => {
  const code = Array.isArray(route.query.error) ? route.query.error[0] : route.query.error
  if (!code) return null
  return code === 'access_denied'
    ? 'Access was denied at the provider. Try again, or use another sign-in method.'
    : 'Something went wrong while signing in with your provider. Try again, or use another sign-in method.'
})

// Where the OIDC flow lands afterwards; the API validates it is an app-relative path.
const oidcHref = (id: string) => `/api/v1/auth/oidc/${encodeURIComponent(id)}/start?redirect=${encodeURIComponent(redirect.value)}`

const hasOtherMethods = computed(() => !!providers.value && (providers.value.magicLink || providers.value.oidc.length > 0))

function focusFirstInvalid(event: FormErrorEvent) {
  const id = event.errors[0]?.id
  if (id) document.getElementById(id)?.focus()
}

// Email + password
const passwordSchema = z.object({
  email: z.email('Enter a valid email address, like name@example.com'),
  password: z.string().min(1, 'Enter your password')
})
const credentials = reactive({ email: '', password: '' })
const signInError = ref<string | null>(null)
const signingIn = ref(false)

async function onSignIn(event: FormSubmitEvent<z.output<typeof passwordSchema>>) {
  signingIn.value = true
  signInError.value = null
  const r = await signIn(event.data.email, event.data.password)
  signingIn.value = false
  if (r.ok) await navigateTo(redirect.value)
  else signInError.value = r.message
}

// Magic link
const linkSchema = z.object({ email: z.email('Enter a valid email address, like name@example.com') })
const link = reactive({ email: '' })
const linkError = ref<string | null>(null)
const linkSentTo = ref<string | null>(null)
const sendingLink = ref(false)

async function onSendLink(event: FormSubmitEvent<z.output<typeof linkSchema>>) {
  sendingLink.value = true
  linkError.value = null
  const r = await requestMagicLink(event.data.email)
  sendingLink.value = false
  if (r.ok) linkSentTo.value = event.data.email
  else linkError.value = r.message
}
</script>

<template>
  <div class="space-y-6">
    <h1 class="text-2xl font-semibold text-balance">
      Sign in
    </h1>

    <UAlert
      v-if="providerError"
      data-testid="provider-error"
      role="alert"
      color="error"
      variant="subtle"
      title="Couldn't sign you in"
      :description="providerError"
    />

    <div v-if="status === 'idle' || status === 'loading'" data-testid="providers-loading" class="space-y-3" aria-busy="true">
      <USkeleton class="h-9 w-full" />
      <USkeleton class="h-9 w-full" />
      <USkeleton class="h-9 w-full" />
    </div>

    <UAlert
      v-else-if="status === 'error' || !providers"
      data-testid="providers-error"
      role="alert"
      color="error"
      variant="subtle"
      title="Couldn't load the sign-in options"
      description="The server didn't respond. Check your connection, then try again."
      :actions="[{ label: 'Try again', color: 'neutral', variant: 'outline', onClick: load }]"
    />

    <template v-else>
      <UForm
        v-if="providers.password"
        :schema="passwordSchema"
        :state="credentials"
        class="space-y-4"
        @submit="onSignIn"
        @error="focusFirstInvalid"
      >
        <UFormField label="Email" name="email" required>
          <UInput v-model="credentials.email" type="email" autocomplete="email" class="w-full" />
        </UFormField>
        <UFormField label="Password" name="password" required>
          <UInput v-model="credentials.password" type="password" autocomplete="current-password" class="w-full" />
        </UFormField>
        <UAlert v-if="signInError" role="alert" color="error" variant="subtle" title="Couldn't sign you in" :description="signInError" />
        <UButton type="submit" block :loading="signingIn">
          Sign in
        </UButton>
      </UForm>

      <USeparator v-if="providers.password && hasOtherMethods" label="or" />

      <div v-if="providers.oidc.length" class="space-y-3">
        <UButton
          v-for="p in providers.oidc"
          :key="p.id"
          :to="oidcHref(p.id)"
          external
          block
          color="neutral"
          variant="outline"
          :data-testid="`oidc-${p.id}`"
        >
          Continue with {{ p.name }}
        </UButton>
      </div>

      <div v-if="providers.magicLink">
        <UAlert
          v-if="linkSentTo"
          data-testid="magic-sent"
          role="status"
          color="success"
          variant="subtle"
          title="Check your inbox"
          :description="`If an account exists for ${linkSentTo}, a sign-in link is on its way. It works once and expires soon.`"
        />
        <UForm v-else :schema="linkSchema" :state="link" class="space-y-4" @submit="onSendLink" @error="focusFirstInvalid">
          <UFormField label="Email me a sign-in link" description="No password needed." name="email" required>
            <UInput v-model="link.email" type="email" autocomplete="email" class="w-full" />
          </UFormField>
          <UAlert v-if="linkError" role="alert" color="error" variant="subtle" title="Couldn't send the link" :description="linkError" />
          <UButton type="submit" block color="neutral" variant="outline" :loading="sendingLink">
            Send sign-in link
          </UButton>
        </UForm>
      </div>

      <p v-if="!providers.password && !hasOtherMethods" data-testid="no-methods" class="text-muted">
        No sign-in methods are enabled for this app. Ask an administrator to turn one on.
      </p>

      <p v-if="providers.registration" class="text-sm text-muted">
        New here?
        <ULink :to="{ path: '/register', query: route.query }" class="font-medium text-primary">
          Create an account
        </ULink>
      </p>
    </template>
  </div>
</template>
